version: "3"

services:
  app:
    build: .
    container_name: python
    volumes:
      - ..:/home/python/app
    #command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    command: bash -c "tail -f Initial-Modules-Docker/requirements.txt"
