version: "3"

services:
  app:
    build: .
    container_name: flask_exercise
    ports:
      - 5000:5000
    volumes:
      - .:/home/python/app
    #command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    command: flask run --host=0.0.0.0
